"""Shared fixtures. The database ones are integration-only."""

import os
from pathlib import Path

import pytest
import sqlalchemy as sa
from sqlmodel import Session

from edutap.wallet_apple_vas_web_service.base import SCHEMA

DSN_VARIABLE = "WALLET_APPLE_VAS_WEB_SERVICE_TEST_DSN"

ROOT = Path(__file__).resolve().parent.parent


def _alembic_config(dsn: str):
    """Alembic pointed at the test database rather than at the developer's own.

    The URL is handed over through `sqlalchemy.url` rather than through the
    environment, because `env.py` reads the URL from the Alembic config when it
    carries one and only falls back to the package's `DatabaseSettings`
    otherwise. Setting the environment instead would leave the developer's own
    `EDUTAP_WALLET_APPLE_VAS_WEB_SERVICE_DB_*` variables in play for every
    field the test did not override.
    """
    from alembic.config import Config

    config = Config(str(ROOT / "alembic.ini"))
    config.set_main_option("sqlalchemy.url", dsn)
    return config


def _drop_owned_schema(engine: sa.Engine) -> None:
    """Return the database to the state a fresh deployment finds it in."""
    with engine.begin() as connection:
        connection.execute(sa.schema.DropSchema(SCHEMA, cascade=True, if_exists=True))


@pytest.fixture(scope="module")
def engine():
    """An engine against a throwaway database; skips when none is configured.

    The tables come from `alembic upgrade head`, not from
    `metadata.create_all()`. They are two different DDL paths, and only one of
    them runs in operation: `create_all` would have created the sequence
    `last_update_tag` is drawn from as a side effect of the metadata carrying
    it, and would therefore have kept the whole suite green against a baseline
    migration that omits it -- which is exactly what an autogenerated baseline
    does (see `migrations/versions/0001_initial.py`). Every database-backed
    test in this suite now runs against what a deployment actually gets.
    """
    dsn = os.environ.get(DSN_VARIABLE)
    if not dsn:
        pytest.skip(f"{DSN_VARIABLE} is not set")
    from alembic import command

    engine = sa.create_engine(dsn)
    _drop_owned_schema(engine)
    command.upgrade(_alembic_config(dsn), "head")
    yield engine
    _drop_owned_schema(engine)
    engine.dispose()


@pytest.fixture
def bare_engine():
    """An engine on a database holding none of this package's objects.

    What `engine` is before it has run the migrations, and the state the tests
    *about* the migrations have to start from. Cleans up at setup as well as at
    teardown: the database behind the DSN is a long-lived container rather than
    a per-test one, so a test that left the schema behind would make the next
    one prove nothing.
    """
    dsn = os.environ.get(DSN_VARIABLE)
    if not dsn:
        pytest.skip(f"{DSN_VARIABLE} is not set")
    engine = sa.create_engine(dsn)
    _drop_owned_schema(engine)
    yield engine
    _drop_owned_schema(engine)
    engine.dispose()


@pytest.fixture
def alembic_config(bare_engine):
    """Alembic pointed at `bare_engine`'s database.

    `render_as_string(hide_password=False)` is not a detail: `str(engine.url)`
    masks the password as `***` and the connection then fails to authenticate.
    """
    return _alembic_config(bare_engine.url.render_as_string(hide_password=False))


@pytest.fixture
def alembic_config_in_tmp(tmp_path, bare_engine):
    """`alembic_config`, but with the migration tree copied out of the repository.

    Autogenerate writes a file. Pointed at `migrations/versions/` it would drop
    a revision into the working tree of whoever ran the suite -- and the second
    run would then autogenerate against a tree containing the first run's
    output. The copy is verbatim, `env.py` included, so what runs is the file
    that ships.
    """
    import shutil

    script_location = tmp_path / "migrations"
    shutil.copytree(ROOT / "migrations", script_location)
    config = _alembic_config(bare_engine.url.render_as_string(hide_password=False))
    config.set_main_option("script_location", str(script_location))
    return config


@pytest.fixture
def role_search_path(bare_engine):
    """Return a callable that sets the connecting role's `search_path`.

    `ALTER ROLE ... SET search_path` and not a connection-level `SET`: this is
    the form Ansible uses, it is what a DDL role actually arrives with, and it
    reaches the connection Alembic opens for itself inside `env.py` -- which a
    `SET` on the test's own connection would not.

    Reset on teardown, because the setting outlives the database objects the
    test dropped.
    """
    role = bare_engine.url.username

    def set_to(search_path: str | None) -> None:
        if search_path is None:
            return
        with bare_engine.begin() as connection:
            connection.execute(sa.text(f'ALTER ROLE "{role}" SET search_path TO {search_path}'))

    yield set_to

    with bare_engine.begin() as connection:
        connection.execute(sa.text(f'ALTER ROLE "{role}" RESET search_path'))


@pytest.fixture
def db_session(engine):
    """A session rolled back after each test, so tests cannot see each other."""
    connection = engine.connect()
    transaction = connection.begin()
    with Session(bind=connection) as session:
        yield session
    transaction.rollback()
    connection.close()


@pytest.fixture
def client(db_session):
    """A TestClient whose session, secrets and producer are the test's own."""
    from fastapi import FastAPI
    from fastapi.testclient import TestClient

    from edutap.wallet_apple_vas_web_service import service
    from edutap.wallet_apple_vas_web_service.config import (
        AppleWalletWebServiceSettings,
        get_settings,
    )

    settings = AppleWalletWebServiceSettings(
        authentication_secret="an-issuer-secret",
        producer_pass_url_template=(
            "https://builder.invalid/api/v1/passes/{pass_type_identifier}/{serial_number}"
        ),
        producer_api_token="a-producer-token",
    )

    app = FastAPI()
    app.include_router(service.router)
    app.dependency_overrides[service.get_session] = lambda: db_session
    app.dependency_overrides[get_settings] = lambda: settings
    return TestClient(app)
