"""The migrations are the only way this package's tables come into existence.

Everything here runs against a real PostgreSQL: the properties under test --
that a schema gets created, that the history table lands inside it, that the
sequence exists, and that autogenerate stays off other packages' tables -- are
all properties of the database.

These tests take `bare_engine` rather than the shared `engine` fixture, because
they have to start where a production database starts: with nothing. `engine`
has already run `upgrade head` by the time a test sees it.

The autogenerate tests deliberately drive `alembic.command.revision` rather
than building a `MigrationContext` by hand. A hand-built context is a second
configuration: it can omit `version_table_schema`, forget `render_item`, and
quietly test something production never runs.
"""

from pathlib import Path

import pytest
import sqlalchemy as sa

from edutap.wallet_apple_vas_web_service.base import SCHEMA
from edutap.wallet_apple_vas_web_service.dbdef import VERSION_TABLE, include_name_for

pytestmark = pytest.mark.integration

OUR_TABLES = {"device", "pass", "registration"}

# What the other packages of the shared database look like from here: a history
# table of their own in `public` (the name Alembic gives an unconfigured one), a
# contract table, and a table in somebody else's schema.
FOREIGN_OBJECTS = (
    "CREATE SCHEMA IF NOT EXISTS binding",
    "CREATE TABLE public.alembic_version (version_num varchar(32) NOT NULL)",
    "CREATE TABLE public.person_view_t (id integer)",
    "CREATE TABLE binding.something (id integer)",
)

FOREIGN_CLEANUP = (
    "DROP SCHEMA IF EXISTS binding CASCADE",
    "DROP TABLE IF EXISTS public.alembic_version",
    "DROP TABLE IF EXISTS public.person_view_t",
)


@pytest.fixture(autouse=True)
def no_foreign_leftovers(bare_engine):
    """Remove the planted foreign objects again, before and after every test.

    The database behind the DSN outlives the test run. A `public.person_view_t`
    left behind by one test is invisible to the assertions of the next and
    quietly changes what its autogenerate sees.
    """
    _drop_foreign_objects(bare_engine)
    yield
    _drop_foreign_objects(bare_engine)


def _drop_foreign_objects(engine: sa.Engine) -> None:
    with engine.begin() as connection:
        for statement in FOREIGN_CLEANUP:
            connection.execute(sa.text(statement))


def plant_foreign_objects(engine: sa.Engine) -> None:
    """Fill the database with what the other services keep in it."""
    with engine.begin() as connection:
        for statement in FOREIGN_OBJECTS:
            connection.execute(sa.text(statement))


def autogenerated_body(config, message: str = "check") -> str:
    """Autogenerate a revision and return its `upgrade()` body.

    Drives `alembic.command.revision`, i.e. the same entry point a developer
    types, so `env.py`'s own `context.configure(...)` is what decides the
    outcome -- not a second set of options assembled in the test.

    The body comes back stripped of Alembic's `### commands ###` markers and of
    blank lines, so "proposed nothing" is the empty string rather than a
    shape-dependent comparison.
    """
    from alembic import command

    script = command.revision(config, message=message, autogenerate=True)
    source = Path(script.path).read_text()
    body = source.split("def upgrade() -> None:")[1].split("def downgrade() -> None:")[0]
    lines = [
        line.strip()
        for line in body.splitlines()
        if line.strip() and not line.strip().startswith("#") and '"""' not in line
    ]
    return "\n".join(line for line in lines if line != "pass")


def test_the_migrations_create_the_schema_and_all_three_tables(bare_engine, alembic_config):
    """The path production takes, run against a database that has no schema yet.

    The `CREATE SCHEMA` cannot be left to the first migration: Alembic creates
    its version table before it runs the first revision, so the schema has to
    exist by then. `env.py::create_owned_schemas` does it, and this test starts
    from a database where it is missing.
    """
    from alembic import command

    assert SCHEMA not in sa.inspect(bare_engine).get_schema_names()

    command.upgrade(alembic_config, "head")

    inspector = sa.inspect(bare_engine)
    assert SCHEMA in inspector.get_schema_names()
    assert set(inspector.get_table_names(schema=SCHEMA)) == OUR_TABLES | {VERSION_TABLE}


def test_the_baseline_creates_the_update_tag_sequence(bare_engine, alembic_config):
    """The trap in this baseline, pinned as behaviour.

    Measured against Alembic 1.19.1: `--autogenerate` emits no `CREATE
    SEQUENCE` for a standalone `sa.Sequence`, even one attached to the target
    metadata -- the generated file held three `create_table` calls, one
    `create_index`, and nothing else. `next_update_tag()` draws every
    `last_update_tag` from this sequence, so a baseline left as generated
    deploys green and then fails on the first registration.

    Asserted through `next_update_tag` rather than by looking the sequence up
    in `information_schema`, because the name is not the property that matters:
    the sequence has to be the one this package's code reaches, in the schema
    it reaches it in, and callable by the role the service connects as.
    """
    from alembic import command
    from sqlmodel import Session

    from edutap.wallet_apple_vas_web_service.service import next_update_tag

    command.upgrade(alembic_config, "head")

    with Session(bare_engine) as session:
        first = next_update_tag(session)
        second = next_update_tag(session)

    assert isinstance(first, int)
    assert second > first


def test_the_baseline_creates_the_keys_the_hot_path_needs(bare_engine, alembic_config):
    """Primary keys, both cascading foreign keys and the list endpoint's index.

    Not decoration: `_upsert_device` and `_insert_registration_if_absent`
    depend on `ON CONFLICT` finding a unique index to arbitrate on, and
    `unregister_pass` depends on the device foreign key cascading.
    """
    from alembic import command

    command.upgrade(alembic_config, "head")
    inspector = sa.inspect(bare_engine)

    assert inspector.get_pk_constraint("device", schema=SCHEMA)["constrained_columns"] == [
        "device_library_identifier"
    ]
    assert inspector.get_pk_constraint("pass", schema=SCHEMA)["constrained_columns"] == [
        "pass_type_identifier",
        "serial_number",
    ]
    assert inspector.get_pk_constraint("registration", schema=SCHEMA)["constrained_columns"] == [
        "device_library_identifier",
        "pass_type_identifier",
        "serial_number",
    ]

    cascades = {
        tuple(fk["constrained_columns"]): fk["options"].get("ondelete")
        for fk in inspector.get_foreign_keys("registration", schema=SCHEMA)
    }
    assert cascades == {
        ("device_library_identifier",): "CASCADE",
        ("pass_type_identifier", "serial_number"): "CASCADE",
    }

    indexes = {
        index["name"]: index["column_names"]
        for index in inspector.get_indexes("registration", schema=SCHEMA)
    }
    assert indexes["ix_registration_device_library_identifier"] == [
        "device_library_identifier",
        "pass_type_identifier",
    ]


def test_the_history_table_lives_in_this_packages_schema(bare_engine, alembic_config):
    """Not in a `public.alembic_version` shared with the other packages.

    Several packages writing their history into one table means the second
    package's first migration mistakes the first package's state for its own.
    """
    from alembic import command

    command.upgrade(alembic_config, "head")

    inspector = sa.inspect(bare_engine)
    assert VERSION_TABLE in inspector.get_table_names(schema=SCHEMA)
    assert VERSION_TABLE not in inspector.get_table_names(schema="public")
    assert "alembic_version" not in inspector.get_table_names(schema="public")


@pytest.mark.parametrize(
    "search_path",
    [
        None,
        SCHEMA,
        f'"$user", {SCHEMA}, public',
        f"{SCHEMA}, binding",
    ],
    ids=["role-default", "own-schema-only", "ansible-idiomatic", "two-owners"],
)
def test_autogenerate_proposes_nothing_against_the_database_it_built(
    bare_engine, alembic_config_in_tmp, role_search_path, search_path
):
    """The guard against a migration that drops another service's data.

    Run through the real `env.py`, over the `search_path` settings a DDL role
    plausibly has, against a database holding other packages' objects. After
    `upgrade head` the database is by definition what this package's metadata
    describes, so a correct autogenerate has *nothing* to say -- and that is
    asserted, rather than merely "no drops", because the two ways this can
    break look different:

    * unpinned reflection under `"$user", wallet_apple_vas, public` returns
      `public.alembic_version` and `public.person_view_t` unqualified, the
      bound reads them as this package's schema, and the run emits
      `op.drop_table("alembic_version")` -- with no `schema=`, so applying it
      resolves through the same `search_path` and destroys another package's
      migration history;
    * a bound that assumes `public` instead of reading the connection's default
      schema puts this package's own schema outside itself, and the run emits
      `op.create_table` for all three tables again.

    An empty body is the only outcome that excludes both.
    """
    from alembic import command

    role_search_path(search_path)
    command.upgrade(alembic_config_in_tmp, "head")
    plant_foreign_objects(bare_engine)

    body = autogenerated_body(alembic_config_in_tmp)

    assert "op.drop_" not in body, f"autogenerate would drop foreign objects:\n{body}"
    assert body == "", f"autogenerate proposed changes to a database it just built:\n{body}"


def test_an_unbounded_autogenerate_would_propose_dropping_them(bare_engine, alembic_config):
    """The counterfactual, so the test above cannot pass for the wrong reason.

    Deliberately *not* the configuration `env.py` uses -- that is the point.
    Without the bound, `include_schemas=True` is what turns a routine
    `alembic revision --autogenerate` into a migration that drops another
    service's tables. If this ever stops finding those drops, the planted
    objects have stopped being visible and the test above proves nothing.
    """
    from alembic import command
    from alembic.autogenerate import compare_metadata
    from alembic.migration import MigrationContext

    from edutap.wallet_apple_vas_web_service.base import metadata

    command.upgrade(alembic_config, "head")
    plant_foreign_objects(bare_engine)

    with bare_engine.connect() as connection:
        context = MigrationContext.configure(
            connection=connection,
            opts={"include_schemas": True, "compare_type": True},
        )
        dropped = {
            diff[1].fullname
            for diff in compare_metadata(context, metadata)
            if diff[0] == "remove_table"
        }

    assert {"person_view_t", "binding.something"} <= dropped


def test_the_bound_admits_this_packages_own_tables(bare_engine, alembic_config):
    """The other half of the bound: it must not exclude everything.

    A bound that returned `False` for every name would pass every test about
    foreign objects and be worthless.
    """
    from alembic import command

    command.upgrade(alembic_config, "head")

    with bare_engine.connect() as connection:
        include_name = include_name_for(connection.dialect.default_schema_name)
        reflected = sa.inspect(connection).get_table_names(schema=SCHEMA)

    admitted = {name for name in reflected if include_name(name, "table", {"schema_name": SCHEMA})}
    assert admitted == OUR_TABLES


def test_the_migrations_ask_before_creating_the_schema(bare_engine, alembic_config):
    """A provisioned database must not need `CREATE` on the database itself.

    PostgreSQL checks `CREATE ON DATABASE` before it checks whether the schema
    exists, so an unconditional `CREATE SCHEMA IF NOT EXISTS` fails with
    `InsufficientPrivilege` under exactly the role the estate provisions -- one
    that owns its schema and holds nothing else. The deploy step would die on
    its first statement against a database that is already correct, and so
    would `alembic current`.

    The proxy for that privilege here is the statement count: against a
    database where the schema already exists, no `CREATE SCHEMA` is issued at
    all, so there is no privilege to be denied.
    """
    from alembic import command

    with bare_engine.begin() as connection:
        connection.execute(sa.schema.CreateSchema(SCHEMA))

    issued: list[str] = []

    def record(conn, cursor, statement, parameters, context, executemany):
        if "CREATE SCHEMA" in statement.upper():
            issued.append(statement)

    sa.event.listen(sa.Engine, "before_cursor_execute", record)
    try:
        command.upgrade(alembic_config, "head")
    finally:
        sa.event.remove(sa.Engine, "before_cursor_execute", record)

    assert issued == []


def test_downgrade_removes_every_object_but_leaves_the_history_behind(bare_engine, alembic_config):
    """A baseline that cannot be undone is a baseline nobody dares to try.

    The sequence is part of what has to go: it is created by hand in
    `upgrade()`, so nothing removes it unless `downgrade()` does by hand too.

    What the downgrade does not undo is the schema, and that is not an
    oversight: `DROP SCHEMA ... CASCADE` inside `downgrade()` would take the
    history table with it, and Alembic writes the new head into that table
    *after* the migration function returns. The downgrade would fail on its own
    bookkeeping.
    """
    from alembic import command

    command.upgrade(alembic_config, "head")
    command.downgrade(alembic_config, "base")

    inspector = sa.inspect(bare_engine)
    assert inspector.get_table_names(schema=SCHEMA) == [VERSION_TABLE]
    with bare_engine.connect() as connection:
        remaining = connection.execute(
            sa.text(
                "SELECT sequence_name FROM information_schema.sequences "
                "WHERE sequence_schema = :schema"
            ),
            {"schema": SCHEMA},
        ).all()
    assert remaining == []
