"""initial

The three tables of `edutap.wallet_apple_vas_web_service`, plus the sequence
`last_update_tag` is drawn from, in the `wallet_apple_vas` schema it owns.
Autogenerated against an empty database and read before being accepted: it
creates and it drops nothing else, which is what proves the `include_name`
bound in `env.py` kept it inside this package's own schema.

**The `CREATE SEQUENCE` is hand-written, and it has to be.** Measured against
Alembic 1.19.1: autogenerate does not emit `CREATE SEQUENCE` for a standalone
`sa.Sequence`, not even one attached to the target metadata. The generated file
carried the three tables and the one index and nothing else. A baseline left as
generated therefore deploys green and then fails on the first registration,
inside `next_update_tag()`, with `UndefinedTable: relation
"wallet_apple_vas.update_tag_seq" does not exist` -- after the deploy, in the
request path, which is the worst place to learn it.

There is no `CREATE SCHEMA` here, and there cannot be: Alembic creates its
version table before it runs the first revision, so `wallet_apple_vas` has to
exist before this file is reached. `env.py::create_owned_schemas` does that.

Revision ID: 0001
Revises:
Create Date: 2026-08-16 05:30:44.184224

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Hand-written; see the module docstring. Schema-qualified rather than left
    # to `search_path`, and without `IF NOT EXISTS`: a sequence of this name
    # that already exists in this schema is something this baseline has not
    # accounted for, and adopting it silently is worse than failing here.
    op.execute("CREATE SEQUENCE wallet_apple_vas.update_tag_seq")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "device",
        sa.Column(
            "device_library_identifier", sa.String(length=255, collation="C"), nullable=False
        ),
        sa.Column("push_token", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("device_library_identifier", name=op.f("pk_device")),
        schema="wallet_apple_vas",
    )
    op.create_table(
        "pass",
        sa.Column("pass_type_identifier", sa.String(length=255, collation="C"), nullable=False),
        sa.Column("serial_number", sa.String(length=255, collation="C"), nullable=False),
        sa.Column("last_update_tag", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("pass_type_identifier", "serial_number", name=op.f("pk_pass")),
        schema="wallet_apple_vas",
    )
    op.create_table(
        "registration",
        sa.Column(
            "device_library_identifier", sa.String(length=255, collation="C"), nullable=False
        ),
        sa.Column("pass_type_identifier", sa.String(length=255, collation="C"), nullable=False),
        sa.Column("serial_number", sa.String(length=255, collation="C"), nullable=False),
        sa.Column("delivered_tag", sa.BigInteger(), nullable=True),
        sa.Column("last_pushed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["device_library_identifier"],
            ["wallet_apple_vas.device.device_library_identifier"],
            name=op.f("fk_registration_device_library_identifier_device"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["pass_type_identifier", "serial_number"],
            ["wallet_apple_vas.pass.pass_type_identifier", "wallet_apple_vas.pass.serial_number"],
            name=op.f("fk_registration_pass_type_identifier_pass"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "device_library_identifier",
            "pass_type_identifier",
            "serial_number",
            name=op.f("pk_registration"),
        ),
        schema="wallet_apple_vas",
    )
    op.create_index(
        "ix_registration_device_library_identifier",
        "registration",
        ["device_library_identifier", "pass_type_identifier"],
        unique=False,
        schema="wallet_apple_vas",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    Leaves the `wallet_apple_vas` schema standing, with nothing in it but
    Alembic's own history table. Dropping the schema here would cascade into
    that table, and Alembic writes the new head into it *after* this function
    returns -- the downgrade would fail on its own bookkeeping. Removing the
    schema is a deployment step, not a migration step.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_registration_device_library_identifier",
        table_name="registration",
        schema="wallet_apple_vas",
    )
    op.drop_table("registration", schema="wallet_apple_vas")
    op.drop_table("pass", schema="wallet_apple_vas")
    op.drop_table("device", schema="wallet_apple_vas")
    # ### end Alembic commands ###

    # The other half of the hand-written `CREATE SEQUENCE` above. Autogenerate
    # emitted neither, so neither is inside the markers.
    op.execute("DROP SEQUENCE wallet_apple_vas.update_tag_seq")
